### ISSUE TITLE
Add lint to ban `_italicizeme_` this way in Markdown

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#568]
## Current Behavior
Need to use `<span style="font-style: italic;">` instead of typical Markdown shorthand `_italicizeme_` in this repo

Banning `_italicizeme_` may be possible with custom rule in markdownlint or alex lint, or making our own test.

**Comment by amyrlam** [comment]
FYI @ember-learn/ember-times-editors

**Comment by ijlee2** [comment]
@amyrlam Can you update the PR description to remind us why we have to use `<span style="font-style: italic;">`? I assume the italics don't work somewhere, but wasn't sure where.

It doesn't look like `markdownlint-cli` supports a linting rule for not allowing `_`. I don't think using alex to not allow `_` is a good solution. https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

If this issue is still relevant today (with regards to the upcoming design change for the blog), I think we can manually update `_` to a `<span>` element. What do you think?

**Comment by amyrlam** [comment]
If you write italics in the normal way e.g. literally write `_italicizeme_` in a .md file in this repo, it doesn't appear as italic text, it appears as regular text. Bold works fine though. 

The idea that I have not investigated yet, is that we could hack a solution with some sort of custom regex rule in Markdownlint / alex (that we would not propose as a PR upstream to those libraries), that would solely be for this purpose, until the blog redesign is done.

**Comment by amyrlam** [comment]
@ijlee2 I'm doing a regex search and will tag you in a quick upcoming PR.

**Comment by amyrlam** [comment]
@ijlee2 will fix the alex's on https://github.com/ember-learn/ember-blog/pull/709 later and post it up for review when done!

**Comment by amyrlam** [comment]
@ijlee2 Got the +1 from abhilashlr and merged in https://github.com/ember-learn/ember-blog/pull/709
