### ISSUE TITLE
Discrepancy in release version of when optional jquery is implemented

### ISSUE THREAD

**Issue by jeffreybiles** [ember-learn/ember-blog#65]
## Current Behavior

In [the Ember 3.3 Release blog post](https://blog.emberjs.com/2018/07/16/ember-3-3-released.html), it states that jQuery has been made optional.

However, in [the documentation for optional features](https://guides.emberjs.com/release/configuring-ember/optional-features/#toc_jquery-integration), it states that this feature actually landed in 3.4.

When testing, I am able to remove jQuery in 3.4 but not 3.3.

## Steps to Reproduce

I set the optional feature jquery-integration to false, and then tested in two ways.

1. Does using jQuery throw an error?
2. Does the payload size of vendor.js decrease?

Both of these were true in Ember 3.4 but not in 3.3.

## Possible Solution

This means one of two things:

A) I am misinterpreting what the 3.3 release blog post meant
B) The jQuery-is-optional section of the 3.3 blog post should be moved to the 3.4 blog post

Thanks for all your work on the blog and guides!

**Comment by kennethlarsen** [comment]
Thank you for catching this!

I'm so confused about this (especially since the release notes also states 3.3 https://github.com/emberjs/ember.js/releases/tag/v3.3.0). But if it doesn't even work in 3.3 then that is clearly not the version it was released.

I guess we should look into moving the text from 3.3 to 3.4.
