### ISSUE TITLE
Move Ember Times to Substack / TinyLetter or other service besides Goodbits

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#734]
Why? 
* Goodbits does not honor `{{`. This is a bad UX for RSS readers, or people who refer back to the Goodbits link.
* Shorten the time it takes to convert GitHub ember-blog => mailing

//

- [x] Test out best way to convert Markdown from this repo => TinyLetter 

cc @abhilashlr from the comment today about how h3's had to be manually "adjusted" in Goodbits

Ideally we would have a more 1:1 conversion of Markdown => TinyLetter, similar to the way we do when crossposting to dev.to

cc @ember-learn/ember-times-editors

**Comment by abhilashlr** [comment]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/5667722/89095031-8033b580-d3e7-11ea-86ed-674a9a4d5d63.png">

To add more context, the headers (underlined in the screenshot above) are marked as h3 in markdown (using the `###`), but they appear to be as normal text and this needs a manual change.

**Comment by amyrlam** [comment]
Maybe we should use Buttondown? I made an account, and it supports Markdown (one less thing to convert): https://buttondown.email/features/markdown

I very briefly checked out Buttondown and left some notes purposefully as `// AMYNOTE`. Some Markdown things don't seem to work when copying the raw from https://raw.githubusercontent.com/ember-learn/ember-blog/master/source/2020-07-31-the-ember-times-issue-158.md. See attached:

[Gmail - [PREVIEW] The Ember Times - Issue No. 158.pdf](https://github.com/ember-learn/ember-blog/files/5009950/Gmail.-.PREVIEW.The.Ember.Times.-.Issue.No.158.pdf)

More noting here so can actually make progress on this!

**Comment by abhilashlr** [comment]
> Maybe we should use Buttondown? I made an account, and it supports Markdown (one less thing to convert): https://buttondown.email/features/markdown
> 

I tried Buttondown too. But didn't explore too deep. I can also explore and get back on this @amyrlam

**Comment by abhilashlr** [comment]
> Maybe we should use Buttondown? I made an account, and it supports Markdown (one less thing to convert): https://buttondown.email/features/markdown
> 

Import archives and users: ✅
<img width="997" alt="image" src="https://user-images.githubusercontent.com/5667722/89097291-52f10280-d3fb-11ea-9b34-91503a3028b2.png">

When I manually added subscribers, there was a confirmation email sent to the email ID - this might confuse our existing subscribers. 

> I very briefly checked out Buttondown and left some notes purposefully as `// AMYNOTE`. Some Markdown things don't seem to work when copying the raw from https://raw.githubusercontent.com/ember-learn/ember-blog/master/source/2020-07-31-the-ember-times-issue-158.md. See attached:
> 

It didn't work for me when I copied from GitHub directly either, there were some issues like you've mentioned. So I went back to VSCode and copy-pasted from there and that seems to work fine. We would need to do some manual work in the headers - frontmatter thing in each newsletter.

**Comment by abhilashlr** [comment]
Another thing I noticed is, I tried sending the newsletter to myself, and it ended up in spam. Probably because GMail felt it was a Phishing attack that I sent an email to myself from Buttondown with a reply-to email being my own. So basically the `reply-to` and the `to` were the same and `from` was Buttondown's email. I had subscribed few other email IDs and they all received them properly in inbox (both Gmail and Outlook worked fine) and not in spam.

We might have to customize the reply-to email address as well.
<img width="976" alt="image" src="https://user-images.githubusercontent.com/5667722/89099400-838d6800-d40c-11ea-9f69-d27878f5fa9d.png">

**Comment by amyrlam** [comment]
> So I went back to VSCode and copy-pasted from there and that seems to work fine.

@abhilashlr can you clarify what you mean? I tried copying the .md file from VSCode into Buttondown, but couldn't get that to work well. Maybe I'm missing something?

Really appreciate your help and the push on this BTW!!

***

But...I used the raw markdown from github.com => https://markdowntohtml.com/ and copied it into Tinyletter (didn't work well in Buttondown) and got this, attached, with no manual editing, which seems promising:

[tinyletter-example.pdf](https://github.com/ember-learn/ember-blog/files/5011176/tinyletter-example.pdf)

(Even Goodbits rn, there is manual editing, but our script https://github.com/ember-learn/ember-times-tools helps a lot.)

***

I want to look at this link later, noting here so don't forget: https://zapier.com/blog/markdown-html-export/

**Comment by abhilashlr** [comment]
> @abhilashlr can you clarify what you mean? I tried copying the .md file from VSCode into Buttondown, but couldn't get that to work well. Maybe I'm missing something?
> 

Sure @amyrlam, I should’ve probably explained better, apologies!

So, I first copy-pasted the contents of [GitHub link you had shared](https://raw.githubusercontent.com/ember-learn/ember-blog/master/source/2020-07-31-the-ember-times-issue-158.md) into the textarea for sending the newsletter.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/5667722/89115693-e03e6080-d4a8-11ea-8ba9-67beb6882778.png">

I noticed there were few special characters (escape characters applied for `[]` and so on). As a result, the markdown validation itself failed for the links and it asked me to correct the contents that I pasted as seen in the above screenshot. When I sent that email it was almost similar to what you had shared as a pdf.

To confirm if that was the issue, I pasted the same contents in VSCode but I didn't see any escape characters. This led me to understand that it was the paste mechanism of Buttondown's textarea did some of these transformations under the hood (_maybe_) - although I didn’t dig deep into what caused these escape strings to appear. Then I copy-pasted the contents from VSCode back into the textarea for sending emails and this time the escape characters weren’t present. 

<img width="982" alt="image" src="https://user-images.githubusercontent.com/5667722/89115740-52af4080-d4a9-11ea-8973-01eca89ddbff.png">

I tried sending the newsletter and it was perfect HTML output what I was looking for. 

So I think, instead of copying from the Github source, if we can copy from the editor and paste it into Buttondown, that works well.

I hope that helps 😀 

> But...I used the raw markdown from github.com => https://markdowntohtml.com/ and copied it into Tinyletter (didn't work well in Buttondown) and got this, attached, with no manual editing, which seems promising:
> 
> [tinyletter-example.pdf](https://github.com/ember-learn/ember-blog/files/5011176/tinyletter-example.pdf)
> 

Wow! this newsletter pdf you've shared seems promising. So that means, we convert the markdown to html and then send it via Tinyletter?

**Comment by amyrlam** [comment]
@abhilashlr I've finally gotten to this! I've been testing out Substack, which seems to have some traction. 

I should try https://markdowntohtml.com/ again and see how it works with Substack.

In Substack, it did makes sense to re-copy some things manually if you want "rich" links like tweets and YouTube's embedded in the newsletter. Anyways, let me know what you think if you have cycles! re: https://discord.com/channels/480462759797063690/619289054537711616/788886063698542592

**Comment by amyrlam** [comment]
Done, using https://github.com/ember-learn/ember-blog/issues/899 for follow-ons
