### ISSUE TITLE
broken anchor links in certain articles

### ISSUE THREAD

**Issue by nickschot** [ember-learn/ember-blog#958]
## Current Behavior

Seems these anchor links aren't currently functioning.

## Expected Behavior

Clicking the link should scroll to the relevant section of the article

## Steps to Reproduce

https://blog.emberjs.com/emberjs-native-class-update-2019-edition/ click on one of the links in the list at the top of the article.

**Comment by mansona** [comment]
so the solution to this is to enable "legacy mode" on the markdown parser for IDs (because we probably want to maintain any old links that might have relied on anchors) 

If we add this to the config it should fix it: https://github.com/ember-learn/guides-source/blob/master/config/environment.js#L42-L45

**Comment by wise-introvert** [comment]
@mansona If this hasn't be taken by someone already, I would love to take a shot ( I know it only requires a refactor, as you said, but I'm new to open source and contributing in general and this seems like a "good first issue" )
